Redux Implementation
smigueles/widergy-mobile-training pull request #2
Opened 2021-06-04 19:51 UTC by smigueles

# Summary

- Redux implementation
- You can edit, delete one or clear all expression 

# Test of Case
**The implementation has no paths, so everything happens on the main screen, so there are not many styles.**

# Screenshots
![Captura de pantalla de 2021-06-04 16-22-35](https://user-images.githubusercontent.com/83591613/120853675-6eb0c200-c552-11eb-91ad-604e8c7993d4.png)

# Trello Issue
[https://trello.com/c/PVlp61fs/23-agregando-redux-a-nuestra-app](url)

2021-06-08 17:37 UTC, taltrui requested changes

2021-06-08 17:37 UTC, taltrui commented on src/screens/Display/index.js
> +  clearRegisters,
we don't use mapDispatchToProps, it ends up fragmenting code too much and with the new hooks api there is no equivalent.

2021-06-10 14:59 UTC, lucawidergy requested changes
Bien, mira las observaciones que te hice. Ademas, te recomiendo ya incorporar redux thunks que lo vas a utilzar en la integracion con la api

2021-06-10 14:59 UTC, lucawidergy commented on src/redux/actions.js
> +import {
nosotros solemos usar redux recompose para esto en general. Es algo que menciono seba en su miniclase de redux. 
Para redux recompose, las acciones se suelen crear de la siguiente manera 

import { createTypes, completeTypes } from 'redux-recompose';

export const actions = createTypes(
  completeTypes(
    [
    // aca van las acciones completas ( es decir con failure y success incluidas ya al poner solo el nombre de la accion)
    ],
    [
      // aca van todos las acciones q no son completas
    ]
  ),
  '@@EXPRESIONS'
);

2021-06-10 14:59 UTC, lucawidergy commented on src/redux/reducers/historyReducer.js
> +      registers.push({expresion: action.payload, id: id});
ojo, no estas conservando la inmutabilidad. Recordemos que el store de redux debe ser inmutable

2021-06-10 14:59 UTC, lucawidergy commented on src/redux/reducers/historyReducer.js
> +    case 'SAVE_EXPRESSION': {
para esto creaste las constantes en todo caso. Pero ademas de eso, con lo q te puse de recompose deberias traerte las acciones de ahi. 

Sumado a esto, no esta mal usar un switch como reducer pero en nuestras app estamos usando otra cosa ( switch tambien, pero son reducers viejos que quedaron) que es con redux recompose. 

que va mas o menos asi:

import { createReducer, completeReducer } from 'redux-recompose';


const authReducers = {
  primaryActions: [
    // aca van las acciones primarias, que significa esto? que modifican segun un target por ej, target: deleteExpresion
    tendra un (target)loading, (target)Error y deleteExpression dentro del reducer 
  ],
  override: {
    [actions.ALGUNA_ACCION]: (state, action) =>
      Immutable.merge(state, {
        LO QUE EDITO
      }),
      // ACA PODEMOS EDITAR EL COMPORTAMIENTO DE ALGUNA ACCION , ES DECIR Q NO MODIFICA LO PRIMARIO, SINO LO QUE UNO INDIQUE
     }

2021-06-14 19:21 UTC, lucawidergy requested changes

2021-06-14 19:21 UTC, lucawidergy commented on src/components/CardExpression/index.js
> +        onPress={() => dispatch(actionsCreator.deleteExp(n.id))}
declara esta funcion arriba

2021-06-14 19:21 UTC, lucawidergy commented on src/components/CardExpression/index.js
> +          onPress={
idem con esta accion

2021-06-14 19:21 UTC, lucawidergy commented on src/components/CardExpression/index.js
> +      {show === false ? (
no necesitas porner === false si ya es un booleano, por otro lado TextINput puede estar disabled si !show y listo, no necesitas poner otro componente dependiendo de esta condicion

2021-06-14 19:21 UTC, lucawidergy commented on src/redux/reducers/historyReducer.js
> +let id = 0;
esto no me gusta. Tener una variable globar para el id e ir incrementandola en el reducer no esta para nada bueno

2021-06-14 19:21 UTC, lucawidergy commented on src/redux/reducers/historyReducer.js
> +      return {...state, registers: []};
INITIAL_STATE.registers

2021-06-14 19:21 UTC, lucawidergy commented on src/screens/Display/index.js
> +          onPress={() => dispatch(actionsCreator.saveExp(userText))}
extrae esto y declararo como una funcion arriba

2021-06-14 19:21 UTC, lucawidergy commented on src/screens/Record/index.js
> +    <>
recorda poner fragment

2021-06-14 19:21 UTC, lucawidergy commented on src/screens/Record/index.js
> +            onPress={() => dispatch(actionsCreator.clearRegisters())}
extrae esta funcion

2021-06-14 19:21 UTC, lucawidergy commented on src/redux/reducers/historyReducer.js
> +      const copyRegister = [...registers];
y si hacias un filter mejor?

2021-06-15 15:37 UTC, lucawidergy requested changes
Bien, unos ultimos detalles y estamos

2021-06-15 15:37 UTC, lucawidergy commented on src/components/CardExpression/index.js
> +      {show ? (
aca, podias directamente hacer algo del estilo:

const buttonAction = show? edit: save
const button text = show? edit: save

  <TouchableOpacity onPress={buttonAction} style={styles.btn}>
          <Text style={styles.btnText}>buttonText</Text>
        </TouchableOpacity>

2021-06-15 15:37 UTC, lucawidergy commented on src/components/CardExpression/index.js
> +        <TouchableOpacity onPress={saveCondition()} style={styles.btn}>
ojo, aca estas llamando a saveCondition!

2021-06-15 15:37 UTC, lucawidergy commented on src/screens/Record/index.js
> +          <TouchableOpacity onPress={() => deleteAll()} style={styles?.btnItem}>
```suggestion
          <TouchableOpacity onPress={deleteAll} style={styles?.btnItem}>
```

2021-06-15 18:56 UTC, lucawidergy approved these changes
bien!

2021-06-16 13:13 UTC, taltrui approved these changes

2021-06-16 13:35 UTC, merged