navigation implemented
smigueles/widergy-mobile-training pull request #3
Opened 2021-06-07 19:47 UTC by smigueles

# Summary

- navigation between routes

# Test of Case
N/A

# Screenshots

![Captura de pantalla de 2021-06-07 16-33-37](https://user-images.githubusercontent.com/83591613/121078019-c51a3c80-c7ae-11eb-86e4-277a0bebc766.png)

![Captura de pantalla de 2021-06-07 16-33-42](https://user-images.githubusercontent.com/83591613/121077825-7bc9ed00-c7ae-11eb-8424-bb62170c6289.png)

# Trello Issue
[https://trello.com/c/MovSbLHJ/24-rutas-en-la-app](url)

2021-06-08 17:30 UTC, lucawidergy commented on src/screens/Record/index.js
> +    <>
aunque sea lo mismo, por convencion utilizamos <Fragment> , mas alla de que aca no lo necesitas

2021-06-08 17:41 UTC, lucawidergy requested changes
la navegacion en general esta ok. Lo que si noté que seguramente deberas corregir en el pr de redux es que :
1- el boton add, no funciona
2-el boton edit, si lo clickeas 2 veces queda borrada la expresion, pero sigue ahi el "item"

2021-06-08 17:41 UTC, lucawidergy commented on App.js
> +              headerStyle: {
deberias tener una opciones default, como por ej el background color que lo repetis

2021-06-08 18:39 UTC, smigueles commented on src/screens/Record/index.js
> +    <>
Por conveción que se usa?

2021-06-08 19:36 UTC, smigueles commented
Cambios realizados sobre el estilo en el header de navegación. También se modificó la implementanción de redux

2021-06-09 18:16 UTC, lucawidergy commented on src/screens/Record/index.js
> +    <>
ajajaj, me trolleo esto y borra si pongo entre < > Fragment

2021-06-11 16:57 UTC, lucawidergy approved these changes

2021-06-16 13:16 UTC, taltrui approved these changes

2021-06-16 13:34 UTC, merged