Api integration
smigueles/widergy-mobile-training pull request #4
Opened 2021-06-14 15:43 UTC by smigueles

# Summary

- API Services integration
- An user can get, post, put and delete by an http method

# Test of Case
N/A

# Screenshots
![Captura de pantalla de 2021-06-14 12-02-05](https://user-images.githubusercontent.com/83591613/121919376-59375700-cd0d-11eb-865e-e6b80999d8b0.png)

![Captura de pantalla de 2021-06-14 12-32-43](https://user-images.githubusercontent.com/83591613/121919396-5dfc0b00-cd0d-11eb-8600-cb328e8e5ac6.png)

# Trello Issue

[https://trello.com/c/dOuJ2ev7/25-agregando-servicios-a-la-app](url)

2021-06-16 13:38 UTC, taltrui requested changes

2021-06-16 13:38 UTC, taltrui commented on src/components/CardExpression/index.js
>  const CardExpression = ({n}) => {
What is n??? Be more expressive with names.

2021-06-16 13:38 UTC, taltrui commented on src/redux/historyApi/reducer.js
> +        idMsg: Math.random() * 100,
What is this msg for? Also, using a non-deterministic function inside a reducer, which should be deterministic and pure is a big no-no.

2021-06-16 13:38 UTC, taltrui commented on src/redux/historyApi/reducer.js
> +        idMsg: Math.random() * 100,
Same here

2021-06-16 13:38 UTC, taltrui commented on src/redux/historyApi/reducer.js
> +        idMsg: Math.random() * 100,
And here

2021-06-16 13:38 UTC, taltrui commented on src/screens/Display/index.js
> +
Why this set options? why not directly have the logout in the config of the screen when declaring it?

2021-06-16 13:38 UTC, taltrui commented on src/screens/Record/index.js
> +  }, [historyApi.idMsg]);
This is wrong here, you should get the expressions in the edit/update action, after the success action. Doing this is not a really good approach.

2021-06-16 15:56 UTC, smigueles commented
Changes applied, waiting for a new revision

2021-06-17 15:10 UTC, lucawidergy approved these changes
esta ok, algunos comentario para tener en cuenta para la integracion con redux

1- cuando hago logout, no deberia quedarme cargado el user y la password. 
2- me registre, hice log out y apareci en la pantalla de regitracion y no en login.
3- Validar que haya password/email antes de hacer submit!
4- un loading para el login/logpout
5- en registracion, pone que tengan q confirmar la contraseña y checkea que sean iguales.

2021-06-18 18:31 UTC, taltrui approved these changes

2021-06-18 18:34 UTC, merged